// Generated by cargo xtask gen --lang go
package types


type SubmitParams struct {
    Tx BytesEnvelope `json:"tx"`
    Witnesses []SubmitWitness `json:"witnesses"`
}


type TxEnvelope struct {
    Hash string `json:"hash"`
    Tx string `json:"tx"`
}


type TirInfo struct {
    Bytecode string `json:"bytecode"`
    Encoding string `json:"encoding"`
    Version string `json:"version"`
}


type SubmitResponse struct {
    Hash string `json:"hash"`
}


type SearchSpaceDiagnostic struct {
    ByAddressCount int64 `json:"by_address_count"`
    ByAssetClassCount int64 `json:"by_asset_class_count"`
    ByRefCount int64 `json:"by_ref_count"`
    Matched []string `json:"matched"`
}


type BytesEnvelope struct {
    Encoding string `json:"encoding"`
    Payload string `json:"payload"`
}


type InputQueryDiagnostic struct {
    Address string `json:"address"`
    Collateral bool `json:"collateral"`
    MinAmount map[string]string `json:"min_amount"`
    Refs []string `json:"refs"`
    SupportMany bool `json:"support_many"`
}


type ResolveParams struct {
    Args map[string]interface{} `json:"args"`
    Env map[string]interface{} `json:"env"`
    Tir TirInfo `json:"tir"`
}


type SubmitWitness struct {
    Key BytesEnvelope `json:"key"`
    Signature BytesEnvelope `json:"signature"`
    Type string `json:"type"`
}


type UnsupportedTirDiagnostic struct {
    Expected string `json:"expected"`
    Provided string `json:"provided"`
}


type InputNotResolvedDiagnostic struct {
    Name string `json:"name"`
    Query InputQueryDiagnostic `json:"query"`
    SearchSpace SearchSpaceDiagnostic `json:"search_space"`
}


type MissingTxArgDiagnostic struct {
    Key string `json:"key"`
    Type string `json:"type"`
}


type TxScriptFailureDiagnostic struct {
    Logs []string `json:"logs"`
}

