// Generated by cargo xtask gen --lang ts

export interface SubmitParams {
    tx: BytesEnvelope;
    witnesses: SubmitWitness[];
}


export interface TxEnvelope {
    hash: string;
    tx: string;
}


export interface TirInfo {
    bytecode: string;
    encoding: string;
    version: string;
}


export interface SubmitResponse {
    hash: string;
}


export interface SearchSpaceDiagnostic {
    by_address_count: number | null;
    by_asset_class_count: number | null;
    by_ref_count: number | null;
    matched: string[];
}


export interface BytesEnvelope {
    encoding: string;
    payload: string;
}


export interface InputQueryDiagnostic {
    address: string | null;
    collateral: boolean;
    min_amount: Record<string, string>;
    refs: string[];
    support_many: boolean;
}


export interface ResolveParams {
    args: Record<string, any>;
    env: Record<string, any>;
    tir: TirInfo;
}


export interface SubmitWitness {
    key: BytesEnvelope;
    signature: BytesEnvelope;
    type: "vkey";
}


export interface UnsupportedTirDiagnostic {
    expected: string;
    provided: string;
}


export interface InputNotResolvedDiagnostic {
    name: string;
    query: InputQueryDiagnostic;
    search_space: SearchSpaceDiagnostic;
}


export interface MissingTxArgDiagnostic {
    key: string;
    type: string;
}


export interface TxScriptFailureDiagnostic {
    logs: string[];
}

