# Generated by cargo xtask gen --lang python
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Union, Literal


@dataclass
class UnsupportedTirDiagnostic:
    expected: str
    provided: str


@dataclass
class MissingTxArgDiagnostic:
    key: str
    type: str


@dataclass
class SearchSpaceDiagnostic:
    by_address_count: Optional[int]
    by_asset_class_count: Optional[int]
    by_ref_count: Optional[int]
    matched: List[str]


@dataclass
class InputQueryDiagnostic:
    address: Optional[str]
    collateral: bool
    min_amount: Dict[str, str]
    refs: List[str]
    support_many: bool


@dataclass
class InputNotResolvedDiagnostic:
    name: str
    query: InputQueryDiagnostic
    search_space: SearchSpaceDiagnostic


@dataclass
class TxScriptFailureDiagnostic:
    logs: List[str]


@dataclass
class SubmitWitness:
    key: BytesEnvelope
    signature: BytesEnvelope
    type: Literal["vkey"]


@dataclass
class TxEnvelope:
    hash: str
    tx: str


@dataclass
class BytesEnvelope:
    encoding: str
    payload: str


@dataclass
class SubmitResponse:
    hash: str


@dataclass
class ArgValue:
    pass


@dataclass
class TirInfo:
    bytecode: str
    encoding: str
    version: str


@dataclass
class ArgMap:
    pass

